// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Entites.Models;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Context;

public partial class SmashClubContext : DbContext
{
    public SmashClubContext()
    {
    }

    public SmashClubContext(DbContextOptions<SmashClubContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingStatus> BookingStatuses { get; set; }

    public virtual DbSet<Court> Courts { get; set; }

    public virtual DbSet<CourtCost> CourtCosts { get; set; }

    public virtual DbSet<CourtStatus> CourtStatuses { get; set; }

    public virtual DbSet<EmailConfirm> EmailConfirms { get; set; }

    public virtual DbSet<Facility> Facilities { get; set; }

    public virtual DbSet<FacilityBankAccount> FacilityBankAccounts { get; set; }

    public virtual DbSet<FacilityImage> FacilityImages { get; set; }

    public virtual DbSet<FacilityOperatingHour> FacilityOperatingHours { get; set; }

    public virtual DbSet<FacilityPaymentConfig> FacilityPaymentConfigs { get; set; }

    public virtual DbSet<FacilityReview> FacilityReviews { get; set; }

    public virtual DbSet<FacilityWallet> FacilityWallets { get; set; }

    public virtual DbSet<Feature> Features { get; set; }

    public virtual DbSet<LocalFile> LocalFiles { get; set; }

    public virtual DbSet<MatchAcceptance> MatchAcceptances { get; set; }

    public virtual DbSet<MatchAcceptanceStatus> MatchAcceptanceStatuses { get; set; }

    public virtual DbSet<MatchChallenge> MatchChallenges { get; set; }

    public virtual DbSet<MatchChallengeStatus> MatchChallengeStatuses { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentGateway> PaymentGateways { get; set; }

    public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }

    public virtual DbSet<PayoutRequest> PayoutRequests { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<ScheduleParticipant> ScheduleParticipants { get; set; }

    public virtual DbSet<Sport> Sports { get; set; }

    public virtual DbSet<SportLevel> SportLevels { get; set; }

    public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }

    public virtual DbSet<SubscriptionTier> SubscriptionTiers { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamInvite> TeamInvites { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<TeamMessage> TeamMessages { get; set; }

    public virtual DbSet<TeamRole> TeamRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<UserSportProfile> UserSportProfiles { get; set; }

    public virtual DbSet<UserSubscription> UserSubscriptions { get; set; }

    public virtual DbSet<VideoCallParticipant> VideoCallParticipants { get; set; }

    public virtual DbSet<VideoCallSession> VideoCallSessions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=SmashClub;User ID=sa;Password=12345");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasIndex(e => new { e.CourtId, e.StartTime, e.EndTime }, "IX_Bookings_Court_Time");

            entity.Property(e => e.BookingId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BookingType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("Online");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerNameOffline).HasMaxLength(100);
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.TotalCost)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.BookedByUser).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.BookedByUserId)
                .HasConstraintName("FK_Bookings_Users");

            entity.HasOne(d => d.Court).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CourtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_Courts");

            entity.HasOne(d => d.Status).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_BookingStatus");
        });

        modelBuilder.Entity<BookingStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.ToTable("BookingStatus");

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Court>(entity =>
        {
            entity.Property(e => e.CourtName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Facility).WithMany(p => p.Courts)
                .HasForeignKey(d => d.FacilityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Courts_Facilities");

            entity.HasOne(d => d.Sport).WithMany(p => p.Courts)
                .HasForeignKey(d => d.SportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Courts_Sports");

            entity.HasOne(d => d.Status).WithMany(p => p.Courts)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Courts_CourtStatus");
        });

        modelBuilder.Entity<CourtCost>(entity =>
        {
            entity.HasKey(e => new { e.CourtCostId, e.FacilityId });

            entity.Property(e => e.CourtCostId).ValueGeneratedOnAdd();
            entity.Property(e => e.Cost).HasColumnType("money");
            entity.Property(e => e.DurationMinutes).HasDefaultValue(60);
            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.Court).WithMany(p => p.CourtCosts)
                .HasForeignKey(d => d.CourtId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CourtCosts_Courts");
        });

        modelBuilder.Entity<CourtStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.ToTable("CourtStatus");

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.StatusName).HasMaxLength(50);
        });

        modelBuilder.Entity<EmailConfirm>(entity =>
        {
            entity.HasKey(e => new { e.Code, e.Email });

            entity.Property(e => e.Code)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Facility>(entity =>
        {
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.District)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);

            entity.HasOne(d => d.Owner).WithMany(p => p.Facilities)
                .HasForeignKey(d => d.OwnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Facilities_Users");
        });

        modelBuilder.Entity<FacilityBankAccount>(entity =>
        {
            entity.HasKey(e => e.BankAccountId);

            entity.Property(e => e.AccountHolder)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.AccountNumber)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.BankName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsPrimary).HasDefaultValue(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Facility).WithMany(p => p.FacilityBankAccounts)
                .HasForeignKey(d => d.FacilityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacilityBankAccounts_Facilities");
        });

        modelBuilder.Entity<FacilityImage>(entity =>
        {
            entity.Property(e => e.FacilityImageId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.IsPrimary).HasDefaultValue(false);

            entity.HasOne(d => d.Facility).WithMany(p => p.FacilityImages)
                .HasForeignKey(d => d.FacilityId)
                .HasConstraintName("FK_FacilityImages_Facilities");

            entity.HasOne(d => d.File).WithMany(p => p.FacilityImages)
                .HasForeignKey(d => d.FileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacilityImages_LocalFiles");
        });

        modelBuilder.Entity<FacilityOperatingHour>(entity =>
        {
            entity.HasKey(e => e.OperatingHourId);

            entity.HasOne(d => d.Facility).WithMany(p => p.FacilityOperatingHours)
                .HasForeignKey(d => d.FacilityId)
                .HasConstraintName("FK_FacilityOperatingHours_Facilities");
        });

        modelBuilder.Entity<FacilityPaymentConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigId);

            entity.Property(e => e.ConfigId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsDefault).HasDefaultValue(false);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Facility).WithMany(p => p.FacilityPaymentConfigs)
                .HasForeignKey(d => d.FacilityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacilityPaymentConfigs_Facilities");

            entity.HasOne(d => d.Gateway).WithMany(p => p.FacilityPaymentConfigs)
                .HasForeignKey(d => d.GatewayId)
                .HasConstraintName("FK_FacilityPaymentConfigs_Gateways");
        });

        modelBuilder.Entity<FacilityReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId);

            entity.Property(e => e.ReviewId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Facility).WithMany(p => p.FacilityReviews)
                .HasForeignKey(d => d.FacilityId)
                .HasConstraintName("FK_FacilityReviews_Facilities");

            entity.HasOne(d => d.User).WithMany(p => p.FacilityReviews)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacilityReviews_Users");
        });

        modelBuilder.Entity<FacilityWallet>(entity =>
        {
            entity.HasKey(e => e.FacilityId);

            entity.Property(e => e.FacilityId).ValueGeneratedNever();
            entity.Property(e => e.Balance).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastUpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TotalEarned).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Facility).WithOne(p => p.FacilityWallet)
                .HasForeignKey<FacilityWallet>(d => d.FacilityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FacilityWallets_Facilities");
        });

        modelBuilder.Entity<Feature>(entity =>
        {
            entity.HasIndex(e => e.FeatureCode, "UQ_Features_Code").IsUnique();

            entity.Property(e => e.FeatureCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FeatureName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<LocalFile>(entity =>
        {
            entity.HasKey(e => e.FileId);

            entity.Property(e => e.FileId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FileData).IsRequired();
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FileType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MimeType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Purpose)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasDefaultValue("General");

            entity.HasOne(d => d.UploadedByUser).WithMany(p => p.LocalFiles)
                .HasForeignKey(d => d.UploadedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LocalFiles_Users");
        });

        modelBuilder.Entity<MatchAcceptance>(entity =>
        {
            entity.HasKey(e => e.AcceptanceId);

            entity.HasIndex(e => new { e.ChallengeId, e.ChallengerTeamId }, "UQ_MatchAcceptances_ChallengeTeam").IsUnique();

            entity.Property(e => e.AcceptanceId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DecidedAt).HasColumnType("datetime");
            entity.Property(e => e.StatusId).HasDefaultValue(1);

            entity.HasOne(d => d.Challenge).WithMany(p => p.MatchAcceptances)
                .HasForeignKey(d => d.ChallengeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchAcceptances_Challenges");

            entity.HasOne(d => d.ChallengerTeam).WithMany(p => p.MatchAcceptances)
                .HasForeignKey(d => d.ChallengerTeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchAcceptances_Teams");

            entity.HasOne(d => d.Status).WithMany(p => p.MatchAcceptances)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchAcceptances_Statuses");
        });

        modelBuilder.Entity<MatchAcceptanceStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<MatchChallenge>(entity =>
        {
            entity.HasKey(e => e.ChallengeId);

            entity.Property(e => e.ChallengeId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsCostSplit).HasDefaultValue(true);
            entity.Property(e => e.StatusId).HasDefaultValue(1);
            entity.Property(e => e.TotalCost).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.HostTeam).WithMany(p => p.MatchChallenges)
                .HasForeignKey(d => d.HostTeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchChallenges_HostTeam");

            entity.HasOne(d => d.Schedule).WithMany(p => p.MatchChallenges)
                .HasForeignKey(d => d.ScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchChallenges_Schedules");

            entity.HasOne(d => d.Sport).WithMany(p => p.MatchChallenges)
                .HasForeignKey(d => d.SportId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchChallenges_Sports");

            entity.HasOne(d => d.Status).WithMany(p => p.MatchChallenges)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MatchChallenges_Statuses");
        });

        modelBuilder.Entity<MatchChallengeStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasIndex(e => e.OrderCode, "IX_Payments_OrderCode");

            entity.HasIndex(e => e.OrderCode, "UQ_Payments_OrderCode").IsUnique();

            entity.Property(e => e.PaymentId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.GatewayTransactionId).HasMaxLength(255);
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.PaidAt).HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Gateway");
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.ReferenceId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StatusId).HasDefaultValue(1);

            entity.HasOne(d => d.ConfirmedByUser).WithMany(p => p.PaymentConfirmedByUsers)
                .HasForeignKey(d => d.ConfirmedByUserId)
                .HasConstraintName("FK_Payments_ConfirmedBy");

            entity.HasOne(d => d.FacilityConfig).WithMany(p => p.Payments)
                .HasForeignKey(d => d.FacilityConfigId)
                .HasConstraintName("FK_Payments_FacilityConfigs");

            entity.HasOne(d => d.Gateway).WithMany(p => p.Payments)
                .HasForeignKey(d => d.GatewayId)
                .HasConstraintName("FK_Payments_Gateways");

            entity.HasOne(d => d.Status).WithMany(p => p.Payments)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_PaymentStatuses");

            entity.HasOne(d => d.User).WithMany(p => p.PaymentUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payments_Users");
        });

        modelBuilder.Entity<PaymentGateway>(entity =>
        {
            entity.HasKey(e => e.GatewayId);

            entity.HasIndex(e => e.GatewayCode, "UQ_PaymentGateways_Code").IsUnique();

            entity.Property(e => e.GatewayCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.GatewayName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<PaymentStatus>(entity =>
        {
            entity.HasKey(e => e.StatusId);

            entity.Property(e => e.StatusId).ValueGeneratedNever();
            entity.Property(e => e.StatusName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<PayoutRequest>(entity =>
        {
            entity.HasKey(e => e.PayoutId);

            entity.Property(e => e.PayoutId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Note).HasMaxLength(500);
            entity.Property(e => e.ProcessedAt).HasColumnType("datetime");
            entity.Property(e => e.RequestedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.StatusId).HasDefaultValue(1);
            entity.Property(e => e.TransactionRef).HasMaxLength(100);

            entity.HasOne(d => d.BankAccount).WithMany(p => p.PayoutRequests)
                .HasForeignKey(d => d.BankAccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutRequests_BankAccounts");

            entity.HasOne(d => d.Facility).WithMany(p => p.PayoutRequests)
                .HasForeignKey(d => d.FacilityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PayoutRequests_Facilities");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasIndex(e => e.Token, "UQ_RefreshTokens_Token").IsUnique();

            entity.Property(e => e.RefreshTokenId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(255)
                .HasColumnName("IPAddress");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RefreshTokens_IsActive");
            entity.Property(e => e.JwtId)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RefreshTokens_Users");
        });

        modelBuilder.Entity<Schedule>(entity =>
        {
            entity.Property(e => e.ScheduleId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.BaseCourtCost).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExtraFee)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ExtraFeeNote).HasMaxLength(500);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.TotalCalculatedCost)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Booking).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Schedules_Bookings");

            entity.HasOne(d => d.HostTeam).WithMany(p => p.Schedules)
                .HasForeignKey(d => d.HostTeamId)
                .HasConstraintName("FK_Schedules_HostTeam");
        });

        modelBuilder.Entity<ScheduleParticipant>(entity =>
        {
            entity.HasKey(e => new { e.ScheduleId, e.UserId });

            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Schedule).WithMany(p => p.ScheduleParticipants)
                .HasForeignKey(d => d.ScheduleId)
                .HasConstraintName("FK_ScheduleParticipants_Schedules");

            entity.HasOne(d => d.User).WithMany(p => p.ScheduleParticipants)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ScheduleParticipants_Users");
        });

        modelBuilder.Entity<Sport>(entity =>
        {
            entity.HasIndex(e => e.SportName, "UQ_Sports_SportName").IsUnique();

            entity.Property(e => e.SportName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SportLevel>(entity =>
        {
            entity.HasKey(e => new { e.SportId, e.RankValue });

            entity.Property(e => e.LevelName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Sport).WithMany(p => p.SportLevels)
                .HasForeignKey(d => d.SportId)
                .HasConstraintName("FK_SportLevels_Sports");
        });

        modelBuilder.Entity<SubscriptionPlan>(entity =>
        {
            entity.HasKey(e => e.PlanId);

            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Tier).WithMany(p => p.SubscriptionPlans)
                .HasForeignKey(d => d.TierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SubscriptionPlans_Tiers");
        });

        modelBuilder.Entity<SubscriptionTier>(entity =>
        {
            entity.HasKey(e => e.TierId);

            entity.HasIndex(e => e.TierName, "UQ_SubscriptionTiers_Name").IsUnique();

            entity.Property(e => e.TierName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasMany(d => d.Features).WithMany(p => p.Tiers)
                .UsingEntity<Dictionary<string, object>>(
                    "TierFeature",
                    r => r.HasOne<Feature>().WithMany()
                        .HasForeignKey("FeatureId")
                        .HasConstraintName("FK_TierFeatures_Features"),
                    l => l.HasOne<SubscriptionTier>().WithMany()
                        .HasForeignKey("TierId")
                        .HasConstraintName("FK_TierFeatures_Tiers"),
                    j =>
                    {
                        j.HasKey("TierId", "FeatureId");
                        j.ToTable("TierFeatures");
                    });
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.Property(e => e.TeamId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<TeamInvite>(entity =>
        {
            entity.HasKey(e => e.InviteId);

            entity.HasIndex(e => e.InviteToken, "UQ__TeamInvi__AB4795605EC20C8C").IsUnique();

            entity.Property(e => e.InviteId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentUses).HasDefaultValue(0);
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.InviteToken)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MaxUses).HasDefaultValue(1);

            entity.HasOne(d => d.CreatedByUser).WithMany(p => p.TeamInvites)
                .HasForeignKey(d => d.CreatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamInvites_Users");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamInvites)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_TeamInvites_Teams");
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => new { e.TeamId, e.UserId });

            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_TeamMembers_Teams");

            entity.HasOne(d => d.TeamRole).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamRoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamMembers_TeamRoles");

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_TeamMembers_Users");
        });

        modelBuilder.Entity<TeamMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId);

            entity.Property(e => e.MessageId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.SentAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MediaFile).WithMany(p => p.TeamMessages)
                .HasForeignKey(d => d.MediaFileId)
                .HasConstraintName("FK_TeamMessages_Media");

            entity.HasOne(d => d.Sender).WithMany(p => p.TeamMessages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamMessages_Users");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMessages)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_TeamMessages_Teams");
        });

        modelBuilder.Entity<TeamRole>(entity =>
        {
            entity.Property(e => e.TeamRoleId).ValueGeneratedNever();
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasIndex(e => e.Email, "UQ_Users_Email").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");
            entity.Property(e => e.LastPwdChange)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);

            entity.HasOne(d => d.AvatarFile).WithMany(p => p.Users)
                .HasForeignKey(d => d.AvatarFileId)
                .HasConstraintName("FK_Users_AvatarFile");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_RoleId");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.RoleId);

            entity.Property(e => e.RoleId).ValueGeneratedNever();
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<UserSportProfile>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.SportId });

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.UserSportProfiles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserSportProfiles_Users");

            entity.HasOne(d => d.SportLevel).WithMany(p => p.UserSportProfiles)
                .HasForeignKey(d => new { d.SportId, d.RankValue })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSportProfiles_SportLevels");
        });

        modelBuilder.Entity<UserSubscription>(entity =>
        {
            entity.Property(e => e.UserSubscriptionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.StartDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Plan).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserSubscriptions_Plans");

            entity.HasOne(d => d.User).WithMany(p => p.UserSubscriptions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserSubscriptions_Users");
        });

        modelBuilder.Entity<VideoCallParticipant>(entity =>
        {
            entity.HasKey(e => new { e.SessionId, e.UserId });

            entity.Property(e => e.JoinedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.LeftAt).HasColumnType("datetime");

            entity.HasOne(d => d.Session).WithMany(p => p.VideoCallParticipants)
                .HasForeignKey(d => d.SessionId)
                .HasConstraintName("FK_VideoCallParticipants_Sessions");

            entity.HasOne(d => d.User).WithMany(p => p.VideoCallParticipants)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VideoCallParticipants_Users");
        });

        modelBuilder.Entity<VideoCallSession>(entity =>
        {
            entity.HasKey(e => e.SessionId);

            entity.Property(e => e.SessionId).HasDefaultValueSql("(newid())");
            entity.Property(e => e.EndedAt).HasColumnType("datetime");
            entity.Property(e => e.StartedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.InitiatedByUser).WithMany(p => p.VideoCallSessions)
                .HasForeignKey(d => d.InitiatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VideoCallSessions_Users");

            entity.HasOne(d => d.Team).WithMany(p => p.VideoCallSessions)
                .HasForeignKey(d => d.TeamId)
                .HasConstraintName("FK_VideoCallSessions_Teams");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}