// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Booking
{
    public Guid BookingId { get; set; }

    public int CourtId { get; set; }

    public Guid? BookedByUserId { get; set; }

    public string BookingType { get; set; }

    public string CustomerNameOffline { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal? TotalCost { get; set; }

    public int StatusId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User BookedByUser { get; set; }

    public virtual Court Court { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual BookingStatus Status { get; set; }
}