// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class CourtCost
{
    public int CourtCostId { get; set; }

    public int FacilityId { get; set; }

    public int CourtId { get; set; }

    public int DayOfWeek { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int DurationMinutes { get; set; }

    public decimal Cost { get; set; }

    public bool IsActive { get; set; }

    public virtual Court Court { get; set; }
}