// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Court
{
    public int CourtId { get; set; }

    public int FacilityId { get; set; }

    public int SportId { get; set; }

    public string CourtName { get; set; }

    public int StatusId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CourtCost> CourtCosts { get; set; } = new List<CourtCost>();

    public virtual Facility Facility { get; set; }

    public virtual Sport Sport { get; set; }

    public virtual CourtStatus Status { get; set; }
}