// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class FacilityPaymentConfig
{
    public Guid ConfigId { get; set; }

    public int FacilityId { get; set; }

    public int PaymentModel { get; set; }

    public int? GatewayId { get; set; }

    public string ApiKey { get; set; }

    public string ApiSecret { get; set; }

    public string WebhookUrl { get; set; }

    public bool IsActive { get; set; }

    public bool? IsDefault { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual PaymentGateway Gateway { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}