// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class FacilityImage
{
    public Guid FacilityImageId { get; set; }

    public int FacilityId { get; set; }

    public Guid FileId { get; set; }

    public bool? IsPrimary { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual LocalFile File { get; set; }
}