// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Facility
{
    public int FacilityId { get; set; }

    public Guid OwnerId { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Court> Courts { get; set; } = new List<Court>();

    public virtual User Owner { get; set; }
}