// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Facility
{
    public int FacilityId { get; set; }

    public Guid OwnerId { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string TermsAndRules { get; set; }

    public DateTime? CreatedAt { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<Court> Courts { get; set; } = new List<Court>();

    public virtual ICollection<FacilityBankAccount> FacilityBankAccounts { get; set; } = new List<FacilityBankAccount>();

    public virtual ICollection<FacilityImage> FacilityImages { get; set; } = new List<FacilityImage>();

    public virtual ICollection<FacilityOperatingHour> FacilityOperatingHours { get; set; } = new List<FacilityOperatingHour>();

    public virtual ICollection<FacilityPaymentConfig> FacilityPaymentConfigs { get; set; } = new List<FacilityPaymentConfig>();

    public virtual ICollection<FacilityReview> FacilityReviews { get; set; } = new List<FacilityReview>();

    public virtual FacilityWallet FacilityWallet { get; set; }

    public virtual User Owner { get; set; }

    public virtual ICollection<PayoutRequest> PayoutRequests { get; set; } = new List<PayoutRequest>();
}