// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class FacilityBankAccount
{
    public int BankAccountId { get; set; }

    public int FacilityId { get; set; }

    public string BankName { get; set; }

    public string AccountNumber { get; set; }

    public string AccountHolder { get; set; }

    public bool? IsPrimary { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual ICollection<PayoutRequest> PayoutRequests { get; set; } = new List<PayoutRequest>();
}