// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class FacilityWallet
{
    public int FacilityId { get; set; }

    public decimal Balance { get; set; }

    public decimal TotalEarned { get; set; }

    public DateTime? LastUpdatedAt { get; set; }

    public virtual Facility Facility { get; set; }
}