// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Feature
{
    public int FeatureId { get; set; }

    public string FeatureCode { get; set; }

    public string FeatureName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<SubscriptionTier> Tiers { get; set; } = new List<SubscriptionTier>();
}