// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class LocalFile
{
    public Guid FileId { get; set; }

    public Guid UploadedByUserId { get; set; }

    public string FileName { get; set; }

    public byte[] FileData { get; set; }

    public string FileType { get; set; }

    public long? FileSizeBytes { get; set; }

    public string MimeType { get; set; }

    public string Purpose { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<FacilityImage> FacilityImages { get; set; } = new List<FacilityImage>();

    public virtual ICollection<TeamMessage> TeamMessages { get; set; } = new List<TeamMessage>();

    public virtual User UploadedByUser { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}