// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class MatchChallengeStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<MatchChallenge> MatchChallenges { get; set; } = new List<MatchChallenge>();
}