// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class MatchAcceptance
{
    public Guid AcceptanceId { get; set; }

    public Guid ChallengeId { get; set; }

    public Guid ChallengerTeamId { get; set; }

    public int StatusId { get; set; }

    public DateTime? DecidedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual MatchChallenge Challenge { get; set; }

    public virtual Team ChallengerTeam { get; set; }

    public virtual MatchAcceptanceStatus Status { get; set; }
}