// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class MatchAcceptanceStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<MatchAcceptance> MatchAcceptances { get; set; } = new List<MatchAcceptance>();
}