// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class MatchChallenge
{
    public Guid ChallengeId { get; set; }

    public Guid ScheduleId { get; set; }

    public Guid HostTeamId { get; set; }

    public int SportId { get; set; }

    public int StatusId { get; set; }

    public decimal TotalCost { get; set; }

    public bool IsCostSplit { get; set; }

    public string Message { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Team HostTeam { get; set; }

    public virtual ICollection<MatchAcceptance> MatchAcceptances { get; set; } = new List<MatchAcceptance>();

    public virtual Schedule Schedule { get; set; }

    public virtual Sport Sport { get; set; }

    public virtual MatchChallengeStatus Status { get; set; }
}