// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class PaymentGateway
{
    public int GatewayId { get; set; }

    public string GatewayCode { get; set; }

    public string GatewayName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<FacilityPaymentConfig> FacilityPaymentConfigs { get; set; } = new List<FacilityPaymentConfig>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}