// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Payment
{
    public Guid PaymentId { get; set; }

    public long OrderCode { get; set; }

    public string PaymentType { get; set; }

    public string ReferenceId { get; set; }

    public Guid UserId { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; }

    public int StatusId { get; set; }

    public string PaymentMethod { get; set; }

    public int? GatewayId { get; set; }

    public string GatewayTransactionId { get; set; }

    public Guid? FacilityConfigId { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public Guid? ConfirmedByUserId { get; set; }

    public virtual User ConfirmedByUser { get; set; }

    public virtual FacilityPaymentConfig FacilityConfig { get; set; }

    public virtual PaymentGateway Gateway { get; set; }

    public virtual PaymentStatus Status { get; set; }

    public virtual User User { get; set; }
}