// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class PayoutRequest
{
    public Guid PayoutId { get; set; }

    public int FacilityId { get; set; }

    public decimal Amount { get; set; }

    public int BankAccountId { get; set; }

    public int StatusId { get; set; }

    public string TransactionRef { get; set; }

    public DateTime? RequestedAt { get; set; }

    public DateTime? ProcessedAt { get; set; }

    public string Note { get; set; }

    public virtual FacilityBankAccount BankAccount { get; set; }

    public virtual Facility Facility { get; set; }
}