// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Payout
{
    public Guid PayoutId { get; set; }

    public Guid PaymentId { get; set; }

    public int FacilityId { get; set; }

    public Guid OwnerUserId { get; set; }

    public decimal Amount { get; set; }

    public int StatusId { get; set; }

    public string BankAccountNo { get; set; }

    public string BankName { get; set; }

    public string AccountHolder { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Note { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual User OwnerUser { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual PayoutStatus Status { get; set; }
}
