// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Post
{
    public Guid PostId { get; set; }

    public Guid AuthorUserId { get; set; }

    public int? FacilityId { get; set; }

    public Guid? TeamId { get; set; }

    public int PostType { get; set; }

    public string Content { get; set; }

    public Guid? MediaFileId { get; set; }

    public bool IsBoosted { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User AuthorUser { get; set; }

    public virtual Facility Facility { get; set; }

    public virtual StoredFile MediaFile { get; set; }

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual Team Team { get; set; }
}