// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class PostMedia
{
    public Guid PostId { get; set; }

    public Guid FileId { get; set; }

    public int DisplayOrder { get; set; }

    public virtual StoredFile File { get; set; }

    public virtual Post Post { get; set; }
}