// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class ReportReason
{
    public int ReasonId { get; set; }

    public string ReasonName { get; set; }

    public string Description { get; set; }
}