// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Schedule
{
    public Guid ScheduleId { get; set; }

    public Guid HostTeamId { get; set; }

    public Guid BookingId { get; set; }

    public string Title { get; set; }

    public int MaxParticipants { get; set; }

    public decimal? CostPerPerson { get; set; }

    public string CostNote { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Team HostTeam { get; set; }

    public virtual ICollection<ScheduleParticipant> ScheduleParticipants { get; set; } = new List<ScheduleParticipant>();
}