// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class ScheduleParticipant
{
    public Guid ScheduleId { get; set; }

    public Guid UserId { get; set; }

    public bool IsAttended { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }
}