// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class SportLevel
{
    public int SportId { get; set; }

    public int RankValue { get; set; }

    public string LevelName { get; set; }

    public virtual Sport Sport { get; set; }

    public virtual ICollection<UserSportProfile> UserSportProfiles { get; set; } = new List<UserSportProfile>();
}