// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Sport
{
    public int SportId { get; set; }

    public string SportName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Court> Courts { get; set; } = new List<Court>();

    public virtual ICollection<MatchChallenge> MatchChallenges { get; set; } = new List<MatchChallenge>();

    public virtual ICollection<SportLevel> SportLevels { get; set; } = new List<SportLevel>();
}