// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Sport
{
    public int SportId { get; set; }

    public string SportName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<SportLevel> SportLevels { get; set; } = new List<SportLevel>();

    public virtual ICollection<UserSportProfile> UserSportProfiles { get; set; } = new List<UserSportProfile>();
}