// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class SubscriptionTier
{
    public int TierId { get; set; }

    public string TierName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<SubscriptionPlan> SubscriptionPlans { get; set; } = new List<SubscriptionPlan>();

    public virtual ICollection<Feature> Features { get; set; } = new List<Feature>();
}