// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class SubscriptionPlan
{
    public int PlanId { get; set; }

    public int TierId { get; set; }

    public int DurationMonths { get; set; }

    public decimal Price { get; set; }

    public bool IsActive { get; set; }

    public virtual SubscriptionTier Tier { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}
