// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class TeamInvite
{
    public Guid InviteId { get; set; }

    public Guid TeamId { get; set; }

    public Guid CreatedByUserId { get; set; }

    public string InviteToken { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime ExpiredAt { get; set; }

    public int? MaxUses { get; set; }

    public int? CurrentUses { get; set; }

    public bool? IsActive { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Team Team { get; set; }
}
