// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class Team
{
    public Guid TeamId { get; set; }

    public string TeamName { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MatchAcceptance> MatchAcceptances { get; set; } = new List<MatchAcceptance>();

    public virtual ICollection<MatchChallenge> MatchChallenges { get; set; } = new List<MatchChallenge>();

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<TeamInvite> TeamInvites { get; set; } = new List<TeamInvite>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<TeamMessage> TeamMessages { get; set; } = new List<TeamMessage>();

    public virtual ICollection<VideoCallSession> VideoCallSessions { get; set; } = new List<VideoCallSession>();
}