// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class TeamMessage
{
    public Guid MessageId { get; set; }

    public Guid TeamId { get; set; }

    public Guid SenderId { get; set; }

    public int MessageType { get; set; }

    public string Content { get; set; }

    public Guid? MediaFileId { get; set; }

    public DateTime? SentAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual LocalFile MediaFile { get; set; }

    public virtual User Sender { get; set; }

    public virtual Team Team { get; set; }
}