// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class TeamMember
{
    public Guid TeamId { get; set; }

    public Guid UserId { get; set; }

    public int TeamRoleId { get; set; }

    public int Wins { get; set; }

    public int Losses { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Team Team { get; set; }

    public virtual TeamRole TeamRole { get; set; }

    public virtual User User { get; set; }
}
