// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public int RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime LastPwdChange { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<ScheduleParticipant> ScheduleParticipants { get; set; } = new List<ScheduleParticipant>();

    public virtual ICollection<TeamInvite> TeamInvites { get; set; } = new List<TeamInvite>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<UserSportProfile> UserSportProfiles { get; set; } = new List<UserSportProfile>();
}