// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class UserBlock
{
    public Guid BlockerId { get; set; }

    public Guid BlockedId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Blocked { get; set; }

    public virtual User Blocker { get; set; }
}