// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public int RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string PhoneNumber { get; set; }

    public Guid? AvatarFileId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime LastPwdChange { get; set; }

    public bool? IsActive { get; set; }

    public virtual LocalFile AvatarFile { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Facility> Facilities { get; set; } = new List<Facility>();

    public virtual ICollection<FacilityReview> FacilityReviews { get; set; } = new List<FacilityReview>();

    public virtual ICollection<LocalFile> LocalFiles { get; set; } = new List<LocalFile>();

    public virtual ICollection<Payment> PaymentConfirmedByUsers { get; set; } = new List<Payment>();

    public virtual ICollection<Payment> PaymentUsers { get; set; } = new List<Payment>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<ScheduleParticipant> ScheduleParticipants { get; set; } = new List<ScheduleParticipant>();

    public virtual ICollection<TeamInvite> TeamInvites { get; set; } = new List<TeamInvite>();

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<TeamMessage> TeamMessages { get; set; } = new List<TeamMessage>();

    public virtual ICollection<UserSportProfile> UserSportProfiles { get; set; } = new List<UserSportProfile>();

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();

    public virtual ICollection<VideoCallParticipant> VideoCallParticipants { get; set; } = new List<VideoCallParticipant>();

    public virtual ICollection<VideoCallSession> VideoCallSessions { get; set; } = new List<VideoCallSession>();
}