// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class UserSportProfile
{
    public Guid UserId { get; set; }

    public int SportId { get; set; }

    public int RankValue { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual SportLevel SportLevel { get; set; }

    public virtual User User { get; set; }
}