// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class VideoCallSession
{
    public Guid SessionId { get; set; }

    public Guid TeamId { get; set; }

    public Guid InitiatedByUserId { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public virtual User InitiatedByUser { get; set; }

    public virtual Team Team { get; set; }

    public virtual ICollection<VideoCallParticipant> VideoCallParticipants { get; set; } = new List<VideoCallParticipant>();
}