// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entites.Models;

public partial class VideoCallParticipant
{
    public Guid SessionId { get; set; }

    public Guid UserId { get; set; }

    public DateTime? JoinedAt { get; set; }

    public DateTime? LeftAt { get; set; }

    public virtual VideoCallSession Session { get; set; }

    public virtual User User { get; set; }
}