// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(SmashClubContext))]
    [Migration("20260701165151_RemoveStaleMongoRedisEntities")]
    partial class RemoveStaleMongoRedisEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entites.Models.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("BookedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerNameOffline")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsBookingOffline")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PlatformFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("BookingId");

                    b.HasIndex("BookedByUserId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "CourtId", "StartTime", "EndTime" }, "IX_Bookings_Court_Time");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Entites.Models.BookingStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("BookingStatus", (string)null);
                });

            modelBuilder.Entity("Entites.Models.Court", b =>
                {
                    b.Property<int>("CourtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtId"));

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("CourtId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("SportId");

                    b.HasIndex("StatusId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Entites.Models.CourtCost", b =>
                {
                    b.Property<int>("CourtCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourtCostId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("money");

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("CourtCostId", "FacilityId");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtCosts");
                });

            modelBuilder.Entity("Entites.Models.CourtStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("CourtStatus", (string)null);
                });

            modelBuilder.Entity("Entites.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BusinessCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18, 9)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18, 9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TermsAndRules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilityId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Entites.Models.FacilityBankAccount", b =>
                {
                    b.Property<int>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankAccountId"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("BankAccountId");

                    b.HasIndex("FacilityId");

                    b.ToTable("FacilityBankAccounts");
                });

            modelBuilder.Entity("Entites.Models.FacilityImage", b =>
                {
                    b.Property<Guid>("FacilityImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("FacilityImageId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("FileId");

                    b.ToTable("FacilityImages");
                });

            modelBuilder.Entity("Entites.Models.FacilityOperatingHour", b =>
                {
                    b.Property<int>("OperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatingHourId"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("OperatingHourId");

                    b.HasIndex("FacilityId");

                    b.ToTable("FacilityOperatingHours");
                });

            modelBuilder.Entity("Entites.Models.FacilityPaymentConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("GatewayId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PaymentModel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfigId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("GatewayId");

                    b.ToTable("FacilityPaymentConfigs");
                });

            modelBuilder.Entity("Entites.Models.FacilityReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("FacilityReviews");
                });

            modelBuilder.Entity("Entites.Models.FacilityStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("FacilityStatuses");
                });

            modelBuilder.Entity("Entites.Models.FacilityWallet", b =>
                {
                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TotalEarned")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("FacilityId");

                    b.ToTable("FacilityWallets");
                });

            modelBuilder.Entity("Entites.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FeatureId");

                    b.HasIndex(new[] { "FeatureCode" }, "UQ_Features_Code")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Entites.Models.MatchAcceptance", b =>
                {
                    b.Property<Guid>("AcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengerTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("AcceptanceId");

                    b.HasIndex("ChallengerTeamId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "ChallengeId", "ChallengerTeamId" }, "UQ_MatchAcceptances_ChallengeTeam")
                        .IsUnique();

                    b.ToTable("MatchAcceptances");
                });

            modelBuilder.Entity("Entites.Models.MatchAcceptanceStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("MatchAcceptanceStatuses");
                });

            modelBuilder.Entity("Entites.Models.MatchChallenge", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("HostTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCostSplit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ChallengeId");

                    b.HasIndex("HostTeamId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SportId");

                    b.HasIndex("StatusId");

                    b.ToTable("MatchChallenges");
                });

            modelBuilder.Entity("Entites.Models.MatchChallengeStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("MatchChallengeStatuses");
                });

            modelBuilder.Entity("Entites.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("FacilityConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GatewayId")
                        .HasColumnType("int");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Gateway");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PlatformFee")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("FacilityConfigId");

                    b.HasIndex("GatewayId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrderCode" }, "IX_Payments_OrderCode");

                    b.HasIndex(new[] { "OrderCode" }, "UQ_Payments_OrderCode")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Entites.Models.PaymentGateway", b =>
                {
                    b.Property<int>("GatewayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GatewayId"));

                    b.Property<string>("GatewayCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("GatewayId");

                    b.HasIndex(new[] { "GatewayCode" }, "UQ_PaymentGateways_Code")
                        .IsUnique();

                    b.ToTable("PaymentGateways");
                });

            modelBuilder.Entity("Entites.Models.PaymentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("Entites.Models.Payout", b =>
                {
                    b.Property<Guid>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("AccountHolder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BankAccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("PayoutId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StatusId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("Entites.Models.PayoutRequest", b =>
                {
                    b.Property<Guid>("PayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PayoutId");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("FacilityId");

                    b.ToTable("PayoutRequests");
                });

            modelBuilder.Entity("Entites.Models.PayoutStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("PayoutStatuses");
                });

            modelBuilder.Entity("Entites.Models.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal>("BaseCourtCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("ExtraFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ExtraFeeNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HostTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TotalCalculatedCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("ScheduleId");

                    b.HasIndex("BookingId");

                    b.HasIndex("HostTeamId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Entites.Models.ScheduleParticipant", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostToPay")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ScheduleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleParticipants");
                });

            modelBuilder.Entity("Entites.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SportId");

                    b.HasIndex(new[] { "SportName" }, "UQ_Sports_SportName")
                        .IsUnique();

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Entites.Models.SportLevel", b =>
                {
                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("RankValue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SportId", "RankValue");

                    b.ToTable("SportLevels");
                });

            modelBuilder.Entity("Entites.Models.StoredFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("FileType")
                        .HasColumnType("tinyint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)4);

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FileId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("Entites.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("DurationMonths")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.HasIndex("TierId");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("Entites.Models.SubscriptionTier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TierId");

                    b.HasIndex(new[] { "TierName" }, "UQ_SubscriptionTiers_Name")
                        .IsUnique();

                    b.ToTable("SubscriptionTiers");
                });

            modelBuilder.Entity("Entites.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SettingKey");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Entites.Models.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TeamId");

                    b.HasIndex("AvatarFileId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Entites.Models.TeamInvite", b =>
                {
                    b.Property<Guid>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CurrentUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime");

                    b.Property<string>("InviteToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxUses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InviteId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "InviteToken" }, "UQ__TeamInvi__AB4795603D42F134")
                        .IsUnique();

                    b.ToTable("TeamInvites");
                });

            modelBuilder.Entity("Entites.Models.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("TeamRoleId")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("TeamRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Entites.Models.TeamRole", b =>
                {
                    b.Property<int>("TeamRoleId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamRoleId");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("Entites.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("AvatarFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BanReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BanUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cccd")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_IsActive");

                    b.Property<DateTime>("LastPwdChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AvatarFileId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entites.Models.UserBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId");

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("Entites.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Entites.Models.UserSportProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<int>("RankValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "SportId");

                    b.HasIndex("SportId", "RankValue");

                    b.ToTable("UserSportProfiles");
                });

            modelBuilder.Entity("Entites.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("UserSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTrial")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Entites.Models.VideoCallParticipant", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime");

                    b.HasKey("SessionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("VideoCallParticipants");
                });

            modelBuilder.Entity("Entites.Models.VideoCallSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("VideoCallSessions");
                });

            modelBuilder.Entity("TierFeature", b =>
                {
                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("TierId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("TierFeatures", (string)null);
                });

            modelBuilder.Entity("Entites.Models.Booking", b =>
                {
                    b.HasOne("Entites.Models.User", "BookedByUser")
                        .WithMany("Bookings")
                        .HasForeignKey("BookedByUserId")
                        .HasConstraintName("FK_Bookings_Users");

                    b.HasOne("Entites.Models.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Courts");

                    b.HasOne("Entites.Models.BookingStatus", "Status")
                        .WithMany("Bookings")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_BookingStatus");

                    b.Navigation("BookedByUser");

                    b.Navigation("Court");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.Court", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("Courts")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Courts_Facilities");

                    b.HasOne("Entites.Models.Sport", "Sport")
                        .WithMany("Courts")
                        .HasForeignKey("SportId")
                        .IsRequired()
                        .HasConstraintName("FK_Courts_Sports");

                    b.HasOne("Entites.Models.CourtStatus", "Status")
                        .WithMany("Courts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Courts_CourtStatus");

                    b.Navigation("Facility");

                    b.Navigation("Sport");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.CourtCost", b =>
                {
                    b.HasOne("Entites.Models.Court", "Court")
                        .WithMany("CourtCosts")
                        .HasForeignKey("CourtId")
                        .IsRequired()
                        .HasConstraintName("FK_CourtCosts_Courts");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Entites.Models.Facility", b =>
                {
                    b.HasOne("Entites.Models.User", "Owner")
                        .WithMany("Facilities")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Facilities_Users");

                    b.HasOne("Entites.Models.FacilityStatus", "Status")
                        .WithMany("Facilities")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Facilities_Statuses");

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.FacilityBankAccount", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("FacilityBankAccounts")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_FacilityBankAccounts_Facilities");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Entites.Models.FacilityImage", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("FacilityImages")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FacilityImages_Facilities");

                    b.HasOne("Entites.Models.StoredFile", "File")
                        .WithMany("FacilityImages")
                        .HasForeignKey("FileId")
                        .IsRequired()
                        .HasConstraintName("FK_FacilityImages_StoredFiles");

                    b.Navigation("Facility");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Entites.Models.FacilityOperatingHour", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("FacilityOperatingHours")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FacilityOperatingHours_Facilities");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Entites.Models.FacilityPaymentConfig", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("FacilityPaymentConfigs")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_FacilityPaymentConfigs_Facilities");

                    b.HasOne("Entites.Models.PaymentGateway", "Gateway")
                        .WithMany("FacilityPaymentConfigs")
                        .HasForeignKey("GatewayId")
                        .HasConstraintName("FK_FacilityPaymentConfigs_Gateways");

                    b.Navigation("Facility");

                    b.Navigation("Gateway");
                });

            modelBuilder.Entity("Entites.Models.FacilityReview", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("FacilityReviews")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FacilityReviews_Facilities");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("FacilityReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_FacilityReviews_Users");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.FacilityWallet", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithOne("FacilityWallet")
                        .HasForeignKey("Entites.Models.FacilityWallet", "FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_FacilityWallets_Facilities");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Entites.Models.MatchAcceptance", b =>
                {
                    b.HasOne("Entites.Models.MatchChallenge", "Challenge")
                        .WithMany("MatchAcceptances")
                        .HasForeignKey("ChallengeId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchAcceptances_Challenges");

                    b.HasOne("Entites.Models.Team", "ChallengerTeam")
                        .WithMany("MatchAcceptances")
                        .HasForeignKey("ChallengerTeamId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchAcceptances_Teams");

                    b.HasOne("Entites.Models.MatchAcceptanceStatus", "Status")
                        .WithMany("MatchAcceptances")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchAcceptances_Statuses");

                    b.Navigation("Challenge");

                    b.Navigation("ChallengerTeam");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.MatchChallenge", b =>
                {
                    b.HasOne("Entites.Models.Team", "HostTeam")
                        .WithMany("MatchChallenges")
                        .HasForeignKey("HostTeamId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchChallenges_HostTeam");

                    b.HasOne("Entites.Models.Schedule", "Schedule")
                        .WithMany("MatchChallenges")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchChallenges_Schedules");

                    b.HasOne("Entites.Models.Sport", "Sport")
                        .WithMany("MatchChallenges")
                        .HasForeignKey("SportId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchChallenges_Sports");

                    b.HasOne("Entites.Models.MatchChallengeStatus", "Status")
                        .WithMany("MatchChallenges")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_MatchChallenges_Statuses");

                    b.Navigation("HostTeam");

                    b.Navigation("Schedule");

                    b.Navigation("Sport");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.Payment", b =>
                {
                    b.HasOne("Entites.Models.User", "ConfirmedByUser")
                        .WithMany("PaymentConfirmedByUsers")
                        .HasForeignKey("ConfirmedByUserId")
                        .HasConstraintName("FK_Payments_ConfirmedBy");

                    b.HasOne("Entites.Models.FacilityPaymentConfig", "FacilityConfig")
                        .WithMany("Payments")
                        .HasForeignKey("FacilityConfigId")
                        .HasConstraintName("FK_Payments_FacilityConfigs");

                    b.HasOne("Entites.Models.PaymentGateway", "Gateway")
                        .WithMany("Payments")
                        .HasForeignKey("GatewayId")
                        .HasConstraintName("FK_Payments_Gateways");

                    b.HasOne("Entites.Models.PaymentStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_PaymentStatuses");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("PaymentUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("FacilityConfig");

                    b.Navigation("Gateway");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.Payout", b =>
                {
                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("Payouts")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_Facilities");

                    b.HasOne("Entites.Models.User", "OwnerUser")
                        .WithMany("Payouts")
                        .HasForeignKey("OwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_Users");

                    b.HasOne("Entites.Models.Payment", "Payment")
                        .WithMany("Payouts")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_Payments");

                    b.HasOne("Entites.Models.PayoutStatus", "Status")
                        .WithMany("Payouts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Payouts_PayoutStatuses");

                    b.Navigation("Facility");

                    b.Navigation("OwnerUser");

                    b.Navigation("Payment");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Entites.Models.PayoutRequest", b =>
                {
                    b.HasOne("Entites.Models.FacilityBankAccount", "BankAccount")
                        .WithMany("PayoutRequests")
                        .HasForeignKey("BankAccountId")
                        .IsRequired()
                        .HasConstraintName("FK_PayoutRequests_BankAccounts");

                    b.HasOne("Entites.Models.Facility", "Facility")
                        .WithMany("PayoutRequests")
                        .HasForeignKey("FacilityId")
                        .IsRequired()
                        .HasConstraintName("FK_PayoutRequests_Facilities");

                    b.Navigation("BankAccount");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Entites.Models.Schedule", b =>
                {
                    b.HasOne("Entites.Models.Booking", "Booking")
                        .WithMany("Schedules")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Bookings");

                    b.HasOne("Entites.Models.Team", "HostTeam")
                        .WithMany("Schedules")
                        .HasForeignKey("HostTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_HostTeam");

                    b.Navigation("Booking");

                    b.Navigation("HostTeam");
                });

            modelBuilder.Entity("Entites.Models.ScheduleParticipant", b =>
                {
                    b.HasOne("Entites.Models.Schedule", "Schedule")
                        .WithMany("ScheduleParticipants")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleParticipants_Schedules");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("ScheduleParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ScheduleParticipants_Users");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.SportLevel", b =>
                {
                    b.HasOne("Entites.Models.Sport", "Sport")
                        .WithMany("SportLevels")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SportLevels_Sports");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Entites.Models.StoredFile", b =>
                {
                    b.HasOne("Entites.Models.User", "UploadedByUser")
                        .WithMany("StoredFiles")
                        .HasForeignKey("UploadedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_StoredFiles_Users");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Entites.Models.SubscriptionPlan", b =>
                {
                    b.HasOne("Entites.Models.SubscriptionTier", "Tier")
                        .WithMany("SubscriptionPlans")
                        .HasForeignKey("TierId")
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionPlans_Tiers");

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("Entites.Models.Team", b =>
                {
                    b.HasOne("Entites.Models.StoredFile", "AvatarFile")
                        .WithMany("Teams")
                        .HasForeignKey("AvatarFileId")
                        .HasConstraintName("FK_Teams_AvatarFile");

                    b.Navigation("AvatarFile");
                });

            modelBuilder.Entity("Entites.Models.TeamInvite", b =>
                {
                    b.HasOne("Entites.Models.User", "CreatedByUser")
                        .WithMany("TeamInvites")
                        .HasForeignKey("CreatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_TeamInvites_Users");

                    b.HasOne("Entites.Models.Team", "Team")
                        .WithMany("TeamInvites")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamInvites_Teams");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Entites.Models.TeamMember", b =>
                {
                    b.HasOne("Entites.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamMembers_Teams");

                    b.HasOne("Entites.Models.TeamRole", "TeamRole")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_TeamMembers_TeamRoles");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamMembers_Users");

                    b.Navigation("Team");

                    b.Navigation("TeamRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.User", b =>
                {
                    b.HasOne("Entites.Models.StoredFile", "AvatarFile")
                        .WithMany("Users")
                        .HasForeignKey("AvatarFileId")
                        .HasConstraintName("FK_Users_AvatarFile");

                    b.HasOne("Entites.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_RoleId");

                    b.Navigation("AvatarFile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entites.Models.UserBlock", b =>
                {
                    b.HasOne("Entites.Models.User", "Blocked")
                        .WithMany("UserBlockBlockeds")
                        .HasForeignKey("BlockedId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBlocks_Blocked");

                    b.HasOne("Entites.Models.User", "Blocker")
                        .WithMany("UserBlockBlockers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserBlocks_Blocker");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("Entites.Models.UserSportProfile", b =>
                {
                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("UserSportProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSportProfiles_Users");

                    b.HasOne("Entites.Models.SportLevel", "SportLevel")
                        .WithMany("UserSportProfiles")
                        .HasForeignKey("SportId", "RankValue")
                        .IsRequired()
                        .HasConstraintName("FK_UserSportProfiles_SportLevels");

                    b.Navigation("SportLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.UserSubscription", b =>
                {
                    b.HasOne("Entites.Models.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscriptions_Plans");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSubscriptions_Users");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.VideoCallParticipant", b =>
                {
                    b.HasOne("Entites.Models.VideoCallSession", "Session")
                        .WithMany("VideoCallParticipants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoCallParticipants_Sessions");

                    b.HasOne("Entites.Models.User", "User")
                        .WithMany("VideoCallParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_VideoCallParticipants_Users");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.VideoCallSession", b =>
                {
                    b.HasOne("Entites.Models.User", "InitiatedByUser")
                        .WithMany("VideoCallSessions")
                        .HasForeignKey("InitiatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_VideoCallSessions_Users");

                    b.HasOne("Entites.Models.Team", "Team")
                        .WithMany("VideoCallSessions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VideoCallSessions_Teams");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TierFeature", b =>
                {
                    b.HasOne("Entites.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TierFeatures_Features");

                    b.HasOne("Entites.Models.SubscriptionTier", null)
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TierFeatures_Tiers");
                });

            modelBuilder.Entity("Entites.Models.Booking", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Entites.Models.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Entites.Models.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CourtCosts");
                });

            modelBuilder.Entity("Entites.Models.CourtStatus", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("Entites.Models.Facility", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("FacilityBankAccounts");

                    b.Navigation("FacilityImages");

                    b.Navigation("FacilityOperatingHours");

                    b.Navigation("FacilityPaymentConfigs");

                    b.Navigation("FacilityReviews");

                    b.Navigation("FacilityWallet");

                    b.Navigation("PayoutRequests");

                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("Entites.Models.FacilityBankAccount", b =>
                {
                    b.Navigation("PayoutRequests");
                });

            modelBuilder.Entity("Entites.Models.FacilityPaymentConfig", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Entites.Models.FacilityStatus", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("Entites.Models.MatchAcceptanceStatus", b =>
                {
                    b.Navigation("MatchAcceptances");
                });

            modelBuilder.Entity("Entites.Models.MatchChallenge", b =>
                {
                    b.Navigation("MatchAcceptances");
                });

            modelBuilder.Entity("Entites.Models.MatchChallengeStatus", b =>
                {
                    b.Navigation("MatchChallenges");
                });

            modelBuilder.Entity("Entites.Models.Payment", b =>
                {
                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("Entites.Models.PaymentGateway", b =>
                {
                    b.Navigation("FacilityPaymentConfigs");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Entites.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Entites.Models.PayoutStatus", b =>
                {
                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("Entites.Models.Schedule", b =>
                {
                    b.Navigation("MatchChallenges");

                    b.Navigation("ScheduleParticipants");
                });

            modelBuilder.Entity("Entites.Models.Sport", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("MatchChallenges");

                    b.Navigation("SportLevels");
                });

            modelBuilder.Entity("Entites.Models.SportLevel", b =>
                {
                    b.Navigation("UserSportProfiles");
                });

            modelBuilder.Entity("Entites.Models.StoredFile", b =>
                {
                    b.Navigation("FacilityImages");

                    b.Navigation("Teams");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entites.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("Entites.Models.SubscriptionTier", b =>
                {
                    b.Navigation("SubscriptionPlans");
                });

            modelBuilder.Entity("Entites.Models.Team", b =>
                {
                    b.Navigation("MatchAcceptances");

                    b.Navigation("MatchChallenges");

                    b.Navigation("Schedules");

                    b.Navigation("TeamInvites");

                    b.Navigation("TeamMembers");

                    b.Navigation("VideoCallSessions");
                });

            modelBuilder.Entity("Entites.Models.TeamRole", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Entites.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Facilities");

                    b.Navigation("FacilityReviews");

                    b.Navigation("PaymentConfirmedByUsers");

                    b.Navigation("PaymentUsers");

                    b.Navigation("Payouts");

                    b.Navigation("ScheduleParticipants");

                    b.Navigation("StoredFiles");

                    b.Navigation("TeamInvites");

                    b.Navigation("TeamMembers");

                    b.Navigation("UserBlockBlockeds");

                    b.Navigation("UserBlockBlockers");

                    b.Navigation("UserSportProfiles");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("VideoCallParticipants");

                    b.Navigation("VideoCallSessions");
                });

            modelBuilder.Entity("Entites.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entites.Models.VideoCallSession", b =>
                {
                    b.Navigation("VideoCallParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
